### ISSUE TITLE
Gd2 pod  names are kube1-0, kube2-0, kube3-0

### ISSUE THREAD

**Issue by rmadaka** [gluster/gcs#18]
I have created gcs setup with latest repo using vagrant. i am seeing gd2 pod names like kube1-0, kube2-0, kube3-0. This will create little bit confusion instead of that better to start gd2 pod names with 'gluster'.

**Comment by JohnStrunk** [comment]
I think we can probably prefix the pod names with "gluster". The node name is being added by the templates as we're setting node affinity (kubeN), and the "-0" suffix is due to the StatefulSet.
A quick patch to the template should be able to change the pod names to something like:
`gluster-kube1-0`, etc.

**Comment by Madhu-1** [comment]
i will sent a patch to fix this issue
